<a href="https://colab.research.google.com/github/PuppalaKarthik/karthik_INFO5731_Spring2023/blob/main/In_class_exercise/In_class_exercise_02_02072023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The second In-class-exercise (02/07/2023, 40 points in total)

The purpose of this exercise is to understand users' information needs, then collect data from different sources for analysis.

Question 1 (10 points): Describe an interesting research question (or practical question) you have in mind, what kind of data should be collected to answer the question(s)? How many data needed for the analysis? The detail steps for collecting and save the data.

In [1]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:


Idea: Analyze the ratings of movies and release patterns with the data available in imdb site.

Data to be collected: collect the movie names, genre, rank, rating, description, year etc


Number of data needed: To analyze the data and identify patterns over it, we need large amount of data.

Steps for collecting and saving the data:

1. Identify the URL of the movies in the imdb website.

2. Use a web scraper (such as BeautifulSoup in Python) to extract the product information from the HTML of the webpage, including the movie name, rating, year, description, and genre.

3. Filter/clean the data to avoid of storing new line characters or extra spaces.

4. Save the collected information in a .csv file, with columns for movie name, rating, year, description, and genre.

5. Use data analysis techniques (such as pandas in Python) to analyze the collected data, for example by analayzing how the movies are releasing or which genre has good rating.


'''

'\nPlease write you answer here:\n\n\nIdea: Analyze the ratings of movies and release patterns with the data available in imdb site.\n\nData to be collected: collect the movie names, genre, rank, rating, description, year etc\n\n\nNumber of data needed: To analyze the data and identify patterns over it, we need large amount of data.\n\nSteps for collecting and saving the data:\n\n1. Identify the URL of the movies in the imdb website.\n\n2. Use a web scraper (such as BeautifulSoup in Python) to extract the product information from the HTML of the webpage, including the movie name, rating, year, description, and genre.\n\n3. Filter/clean the data to avoid of storing new line characters or extra spaces.\n\n4. Save the collected information in a .csv file, with columns for movie name, rating, year, description, and genre.\n\n5. Use data analysis techniques (such as pandas in Python) to analyze the collected data, for example by analayzing how the movies are releasing or which genre has good rating.\n\n\n'

Question 2 (10 points): Write python code to collect 1000 data samples you discussed above.

In [2]:
# You code here (Please add comments in the code):


from bs4 import BeautifulSoup
import requests
import pandas as pd

In [3]:
data = {
    'rank': [],
    'name': [],
    'year': [],
    'runtime': [],
    'genre': [],
    'rating': [],
    'description': [],
    
}

In [4]:

# start_movie_per_page = 1

# root url
root_url = 'https://www.imdb.com/'

# entry url
url = 'https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=1'
#f'https://www.imdb.com/search/title/?groups=top_1000&sort=user_rating,desc&start={start_movie_per_page}&ref_=adv_nxt'

# headers = {
#     'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'
# }

def get_page_soup_data(url):
    r = requests.get(url)
    soup = BeautifulSoup(r.content, 'html.parser')
    return soup

def get_next_page_url(soup):
    pages_data = soup.find('div', class_='desc')
    if soup.find('div', class_='desc').find('a', class_='lister-page-next next-page'):
        nexturl = root_url + str(soup.find('div', class_='desc').find('a', class_='lister-page-next next-page')['href'])
        return nexturl
    else:
        return

while True:
    # getting soup data of the page
    soup = get_page_soup_data(url)
    
    # Getting all movies list in a page
    movielist = soup.find('div', class_='lister-list').find_all('div', class_='lister-item mode-advanced')
    
    # Iterating all movies in a page
    for movie in movielist:
        name = movie.find('h3', class_ = 'lister-item-header').a.text.strip()
        rank = movie.find('h3', class_='lister-item-header').text.split('.')[0].strip()
        year = movie.find('h3', class_='lister-item-header').find('span', class_='lister-item-year text-muted unbold').text.strip('()')
#         certificate = movie.find_all('p', class_='text-muted')[0].find('span', class_='certificate').text.strip()
        runtime = movie.find_all('p', class_='text-muted')[0].find('span', class_='runtime').text.strip()
        genre  = movie.find_all('p', class_='text-muted')[0].find('span', class_='genre').text.strip()
        rating = movie.find('div', class_='inline-block ratings-imdb-rating').text.strip()
        description = movie.find_all('p', class_='text-muted')[1].text.strip()
#         gross = movie.find('p', class_='sort-num_votes-visible').find_all('span')[4].text.strip()

        # insering data into dict
        data['rank'].append(rank)
        data['name'].append(name)
        data['year'].append(year)
        data['runtime'].append(runtime)
        data['genre'].append(genre)
        data['rating'].append(rating)
        data['description'].append(description)
        
    

    # getting next page url
    url = get_next_page_url(soup)

    print("Next URL: ", url)
    print("Data collected till previous url: ", len(data['rank']))

    # if next page then continuing else aborting
    if not url:
        break

Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=51
Data collected till previous url:  50
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=101
Data collected till previous url:  100
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=151
Data collected till previous url:  150
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=201
Data collected till previous url:  200
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=251
Data collected till previous url:  250
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=301
Data collected till previous url:  300
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=351
Data collected till previous url:  350
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=401
Data collected till previous url:  400
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=451
Data collected till previous url:  450
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=501
Data collected till previous url:  500
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=551
Data collected till previous url:  550
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=601
Data collected till previous url:  600
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=651
Data collected till previous url:  650
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=701
Data collected till previous url:  700
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=751
Data collected till previous url:  750
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=801
Data collected till previous url:  800
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=851
Data collected till previous url:  850
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=901
Data collected till previous url:  900
Next URL:  https://www.imdb.com//search/title/?groups=top_1000&sort=user_rating,desc&start=951
Data collected till previous url:  950
Next URL:  None
Data collected till previous url:  1000

In [5]:
df = pd.DataFrame(data)
df.shape

(1000, 7)

In [6]:
df.tail()

,rank,name,year,runtime,genre,rating,description
995,996,Control,2007,122 min,"Biography, Drama, Music",7.6,"A profile of Ian Curtis, the enigmatic singer ..."
996,997,Philomena,2013,98 min,"Biography, Comedy, Drama",7.6,A world-weary political journalist picks up th...
997,998,The Invisible Man,1933,71 min,"Horror, Sci-Fi",7.6,"A scientist finds a way of becoming invisible,..."
998,999,Shine,1996,105 min,"Biography, Drama, Music",7.6,"Pianist David Helfgott, driven by his father a..."
999,"1,000",Celda 211,2009,113 min,"Action, Adventure, Crime",7.6,The story of two men on different sides of a p...

Question 3 (10 points): Write python code to collect 1000 articles from Google Scholar (https://scholar.google.com/), Microsoft Academic (https://academic.microsoft.com/home), or CiteSeerX (https://citeseerx.ist.psu.edu/index), or Semantic Scholar (https://www.semanticscholar.org/), or ACM Digital Libraries (https://dl.acm.org/) with the keyword "information retrieval". The articles should be published in the last 10 years (2012-2022).

The following information of the article needs to be collected:

(1) Title

(2) Venue/journal/conference being published

(3) Year

(4) Authors

(5) Abstract

In [7]:
# Importing 

import requests
import json

# Search key word
topic = 'information retrieval'

# empty list to store dataframes of every ietration
frames = []

for offset in range(0, 1000, 100):
    url = f"https://api.semanticscholar.org/graph/v1/paper/search?query={topic}&offset={offset}&limit=100&fields=url,title,venue,year,authors,abstract"

    payload={}
    headers = {}
    
    # GET request
    response = requests.request("GET", url, headers=headers, data=payload)
    
    # Storing GET response in a JSON format
    data = json.loads(response.text)['data']

    # generating df with data requested in above request
    df = pd.DataFrame(data)
    
    # Storing all dataframes in a frames list to concat at the end.
    frames.append(df) 

# concating all Dataframes availabl in frames list
main_df = pd.concat(frames)
# Resetting index of main df after concating all dataframes available in frames list.
main_df.reset_index(drop=True)

,paperId,url,title,abstract,venue,year,authors
0,5f3b50c6c826ad105163b09d53e1eb498a4b3994,https://www.semanticscholar.org/paper/5f3b50c6...,Introduction to Information Retrieval,Introduction To Information Retrieval Overdriv...,J. Assoc. Inf. Sci. Technol.,2010.0,"[{'authorId': '1803434', 'name': 'R. Larson'}]"
1,807600ef43073cd9c59d4208ee710e90cf14efa8,https://www.semanticscholar.org/paper/807600ef...,BEIR: A Heterogenous Benchmark for Zero-shot E...,Existing neural information retrieval (IR) mod...,NeurIPS Datasets and Benchmarks,2021.0,"[{'authorId': '47583894', 'name': 'Nandan Thak..."
2,806c2c4327a31fded64a5d673ab82b133194c234,https://www.semanticscholar.org/paper/806c2c43...,Introduction to information retrieval,"Class-tested and coherent, this textbook teach...",,2008.0,"[{'authorId': '144783904', 'name': 'Christophe..."
3,49af3e80343eb80c61e727ae0c27541628c7c5e2,https://www.semanticscholar.org/paper/49af3e80...,Introduction to Modern Information Retrieval,Some people may be laughing when looking at yo...,,1983.0,"[{'authorId': '1797808', 'name': 'G. Salton'},..."
4,72c58a58ba1684dc8337c8e64e0b5dacfc94499e,https://www.semanticscholar.org/paper/72c58a58...,Information Retrieval,None,Lecture Notes in Computer Science,2018.0,"[{'authorId': '32293755', 'name': 'A. Dekhtyar'}]"
...,...,...,...,...,...,...,...
995,e5e0a86288a18de079d3d9d53f9018600d2eda5b,https://www.semanticscholar.org/paper/e5e0a862...,Retrieving with Good Sense,None,Information retrieval (Boston),2000.0,"[{'authorId': '144721996', 'name': 'M. Sanders..."
996,c8a95f7414fc6439cf6b3bc8a10f080151e61f78,https://www.semanticscholar.org/paper/c8a95f74...,Concepts and effectiveness of the cover-coeffi...,A new algorithm for document clustering is int...,TODS,1990.0,"[{'authorId': '2083563', 'name': 'F. Can'}, {'..."
997,8e03d064282673120f81c86993466a23af00f037,https://www.semanticscholar.org/paper/8e03d064...,Supporting content-based queries over images i...,While advances in technology allow us to gener...,Proceedings of IEEE International Conference o...,1997.0,"[{'authorId': '144156242', 'name': 'S. Mehrotr..."
998,3f900d6782152e3fe2ecb8f6d9bb12879dacf6e4,https://www.semanticscholar.org/paper/3f900d67...,Case-Based User Profiling for Content Personal...,None,International Conference on Adaptive Hypermedi...,2000.0,"[{'authorId': '144372969', 'name': 'Keith Brad..."
999,228029e7533e32a025071e31e3f4f08d2bea5f5a,https://www.semanticscholar.org/paper/228029e7...,Automatic image annotation and retrieval using...,Libraries have traditionally used manual image...,Annual International ACM SIGIR Conference on R...,2003.0,"[{'authorId': '1791802', 'name': 'J. Jeon'}, {..."

In [8]:
main_df.shape

(1000, 7)

Question 4 (10 points): Write python code to collect 1000 posts from Twitter, or Facebook, or Instagram. You can either use hashtags, keywords, user_name, user_id, or other information to collect the data. 

The following information needs to be collected:

(1) User_name

(2) Posted time

(3) Text

In [9]:
# You code here (Please add comments in the code):

import pandas as pd
import numpy as np
import tweepy
from tweepy import OAuthHandler
import requests
import json


# Secret Keys

consumer_key ="2Em7SxlX9jPMfL4x97r3zMO0x"
consumer_secret = "sVbJzekKuiAgq83Y7gCwNVbSowqQokGVzWexKHl2cXIPceWtSd"
access_token ="1439767876962029572-uUMt8oWRyzj9ilE5zk4uYbL93sCMPT"
access_token_secret = "oydIGymn9bS767FVEMawE9GyGAnMmBJfaY2XXKmHnmliF"

# Authorization
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api_auth = tweepy.API(auth,wait_on_rate_limit=True)
user_name =str(input("Enter the user name\n"))

# Pagination cursor initialization
tweepy_cursor = tweepy.Cursor(api_auth.user_timeline, id=user_name).items(1000)

tweets_list = [[user_name ,tweet.created_at, tweet.text] for tweet in tweepy_cursor]

tweets_df = pd.DataFrame(tweets_list)
tweets_df.columns=['user_name','posted time','text']
tweets_df

Enter the user name
tim_cook

,user_name,posted time,text
0,tim_cook,2023-02-13 03:38:36,"What a game! Congratulations, Kansas City!"
1,tim_cook,2023-02-13 02:37:35,One of the greats! Amazing show from @Rihanna....
2,tim_cook,2023-02-12 16:05:28,I loved spending part of Super Bowl weekend wi...
3,tim_cook,2023-02-10 01:08:20,The first @IndiaArtFair Digital Artists in Res...
4,tim_cook,2023-02-09 20:18:38,There is no dream too big. #AppleMusicHalftime...
...,...,...,...
995,tim_cook,2017-12-09 20:37:07,Thanks to the Apple team for our biggest @Toys...
996,tim_cook,2017-12-09 02:05:05,A huge thanks @gwenstefani for celebrating the...
997,tim_cook,2017-12-08 02:53:03,Imagination and creativity drives us at Apple....
998,tim_cook,2017-12-06 23:23:30,Thank you @JustinTrudeau on behalf of our Cana...
999,tim_cook,2017-12-06 21:33:10,Our thoughts are with our fellow Californians ...